language: python
python:
    - 3.5
    - 3.6
env:
    - PYTHONPATH=.
install:
    - yes | pip uninstall py pytest
    - yes | pip install -U pip setuptools
    - pip install -e .
    - pip install coveralls
script:
    python setup.py test
after_success:
    coveralls
